# Generated by Django 5.0.3 on 2024-03-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_test_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='selected_words',
        ),
        migrations.AddField(
            model_name='test',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
